name: Auxiliary

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]

jobs:
   publish_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Build FileAnalyzer Windows x64
      run: dotnet build /p:Configuration=Release
      working-directory: ./AssetRipper.FileAnalyzer/
      
    - name: Build SystemTester Windows x64
      run: dotnet build /p:Configuration=Release
      working-directory: ./AssetRipper.SystemTester/
      
    - name: Build Tests Windows x64
      run: dotnet build /p:Configuration=Release
      working-directory: ./AssetRipper.Tests/
      
    - name: Run Tests
      run: dotnet test
      working-directory: ./AssetRipper.Tests/
      
    - name: List FileAnalyzer Files
      shell: bash
      run: |
        mkdir -p ./Bins/AssetAnalyzer/Release/Licenses
        cp ./Licenses/*.md ./Bins/AssetAnalyzer/Release/Licenses/
        ls -R ./Bins/AssetAnalyzer/Release
      
    - name: Upload FileAnalyzer Windows x64
      uses: actions/upload-artifact@v3
      with:
        name: FileAnalyzer_win64
        path: D:\a\AssetRipper\AssetRipper\Bins\AssetRipper.FileAnalyzer\Release\*
        if-no-files-found: error
        
    - name: List SystemTester Files
      shell: bash
      run: |
        mkdir -p ./Bins/AssetRipper.SystemTester/Release/Licenses
        cp ./Licenses/*.md ./Bins/AssetRipper.SystemTester/Release/Licenses/
        ls -R ./Bins/AssetRipper.SystemTester/Release

    - name: Upload SystemTester Windows x64
      uses: actions/upload-artifact@v3
      with:
        name: SystemTester_win64
        path: D:\a\AssetRipper\AssetRipper\Bins\AssetRipper.SystemTester\Release\*
        if-no-files-found: error